from __future__ import annotations
from typing import List, Optional

class Store:
    def list_motifs(self, layer: str, user_id: Optional[str]): ...
    def upsert_motifs(self, layer: str, user_id: Optional[str], motifs: list): ...
    def delete_motif(self, layer: str, user_id: Optional[str], motif_id: str): ...
    def link(self, layer: str, user_id: Optional[str], src_id: str, dst_id: str, rel: str = "linked"): ...
    def links_for(self, layer: str, user_id: Optional[str], motif_id: str): ...
    def wipe_namespace(self, layer: str, user_id: Optional[str]): ...
